name       : gnome-desktop-branding
version    : '12'
release    : 13
source     :
    - https://github.com/solus-project/gnome-desktop-branding/releases/download/v12/gnome-desktop-branding-12.tar.xz : beac7b51532a2010824f003d2d997530a6e67992682ef7cd2ad531fe915d83ad
license    : GPL-2.0-only
component  :
    - desktop.gnome
    - material : desktop.gnome
summary    :
    - Defaults for the GNOME Desktop
    - material : Material Design inspired GNOME experience.
description: |
    GNOME Desktop Experience Configuration
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
    - material :
        - /usr/share/glib-2.0/schemas/*material_settings.gschema.override
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - gnome-shell
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-impatience
    - gnome-shell-extensions
    - gnome-shell-extension-topicons-plus
    - plotinus
    - qtstyleplugins
    - solus-artwork
    - material :
        - adapta-gtk-theme
        - gnome-desktop-branding
        - papirus-icon-theme
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
