name       : gnome-desktop-branding
version    : '7'
release    : 9
source     :
    - https://github.com/solus-project/gnome-desktop-branding/releases/download/v7/gnome-desktop-branding-7.tar.xz : eaaa0a097a013873b42e88eacaa2003e0e22d72ad4f2869c81d80c63da2c3d22
license    : GPL-2.0
component  :
    - desktop.gnome
    - material : desktop.gnome
summary    :
    - Defaults for the GNOME Desktop
    - material : Material Design inspired GNOME experience.
description: |
    GNOME Desktop Experience Configuration
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
    - material :
        - /usr/share/glib-2.0/schemas/20_gnome_material_settings.gschema.override
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - gnome-shell
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-impatience
    - gnome-shell-extensions
    - gnome-shell-extension-topicons-plus
    - plotinus
    - qtstyleplugins
    - solus-artwork
    - material :
        - adapta-gtk-theme
        - gnome-desktop-branding
        - papirus-icon-theme
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
