name       : gnome-desktop-branding
version    : '15.2'
release    : 27
source     :
    - git|https://dev.getsol.us/source/gnome-desktop-branding-src.git : def6307f15a9386b8726a569a00fee0d57142021
license    : GPL-2.0-only
component  :
    - desktop.gnome
    - legacy : desktop.gnome
    - livecd : desktop.gnome
    - fortitude : desktop.gnome
    - material : desktop.gnome
    - shared : desktop.gnome
summary    :
    - Defaults for the GNOME Desktop
    - fortitude : Solus 4.0 Fortitude defaults for our GNOME experience
    - legacy : Legacy Solus GNOME desktop branding
    - livecd : Solus 4.0 GNOME LiveCD configuration
    - material : Material Design inspired GNOME experience
    - shared : Shared dependencies of various branding packages
description:
    - Defaults for the GNOME Desktop
    - fortitude : Solus 4.0 Fortitude defaults for our GNOME experience.
    - legacy : Legacy Solus GNOME desktop branding.
    - livecd : Solus 4.0 LiveCD configuration.
    - material : Material Design inspired GNOME experience.
    - shared : Shared dependencies of various branding packages.
patterns   :
    - fortitude :
        - /usr/share/glib-2.0/schemas/30_gnome_fortitude_settings.gschema.override
    - legacy :
        - /usr/share/glib-2.0/schemas/10_gnome_settings.gschema.override
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
    - material :
        - /usr/share/glib-2.0/schemas/20_gnome_material_settings.gschema.override
    - shared :
        - /usr/share/defaults/etc/profile.d/60-gnome-gl.sh
        - /usr/share/gnome-desktop-branding/shared
replaces   :
    - legacy : gnome-desktop-branding
rundeps    :
    - fortitude :
        - gnome-desktop-branding-shared
        - materia-gtk-theme-dark
        - papirus-icon-theme
    - legacy :
        - arc-gtk-theme
        - arc-icon-theme
        - faba-icon-theme-mono
        - gnome-desktop-branding-shared
    - material :
        - adapta-gtk-theme
        - gnome-desktop-branding-legacy
        - papirus-icon-theme
    - shared :
        - breeze-cursor-theme
        - font-clear-sans-ttf
        - gnome-shell
        - gnome-shell-extension-dash-to-dock
        - gnome-shell-extension-impatience
        - gnome-shell-extensions
        - gnome-shell-extension-topicons-plus
        - qtstyleplugins
        - solus-artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    echo "I am just a shared deps package." > $workdir/shared
    install -Dm00644 $workdir/shared $installdir/usr/share/gnome-desktop-branding/shared
