name       : gnome-desktop-branding
version    : '8'
release    : 10
source     :
    - https://github.com/solus-project/gnome-desktop-branding/releases/download/v8/gnome-desktop-branding-8.tar.xz : b079bf94636c8f8244e9879122088d4c4d7d43e89526c69e6d816a6279770a37
license    : GPL-2.0
component  :
    - desktop.gnome
    - material : desktop.gnome
summary    :
    - Defaults for the GNOME Desktop
    - material : Material Design inspired GNOME experience.
description: |
    GNOME Desktop Experience Configuration
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
    - material :
        - /usr/share/glib-2.0/schemas/*material_settings.gschema.override
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - gnome-shell
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-impatience
    - gnome-shell-extensions
    - gnome-shell-extension-topicons-plus
    - plotinus
    - qtstyleplugins
    - solus-artwork
    - material :
        - adapta-gtk-theme
        - gnome-desktop-branding
        - papirus-icon-theme
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
