name       : gnome-desktop-branding
version    : '14'
release    : 17
source     :
    - https://github.com/solus-project/gnome-desktop-branding/releases/download/v14/gnome-desktop-branding-14.tar.xz : b20e3ce490780823917c21d38421b56c7aae62892d447caa60adf3d09bb7d3c4
license    : GPL-2.0-only
component  :
    - desktop.gnome
    - material : desktop.gnome
summary    :
    - Defaults for the GNOME Desktop
    - material : Material Design inspired GNOME experience.
description: |
    GNOME Desktop Experience Configuration
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
    - material :
        - /usr/share/glib-2.0/schemas/*material_settings.gschema.override
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - gnome-shell
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-impatience
    - gnome-shell-extensions
    - gnome-shell-extension-topicons-plus
    - qtstyleplugins
    - solus-artwork
    - material :
        - adapta-gtk-theme
        - gnome-desktop-branding
        - papirus-icon-theme
setup      : |
    %patch -p1 < $pkgfiles/0001-Dropkick-plotinus-on-top-of-v14-to-ensure-graceful-r.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
