name       : gnome-desktop-branding
version    : 2
release    : 3
source     :
    - https://github.com/solus-project/gnome-desktop-branding/releases/download/v2/gnome-desktop-branding-2.tar.xz : 44049af9409e856c40b0c9917caf3f7911d975c44687ad69c2108569cf4d7415
license    : GPL-2.0
component  : desktop.gnome
summary    : Defaults for the GNOME Desktop
description: |
    GNOME Desktop Experience Configuration
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
rundeps    :
    - solus-artwork
    - breeze-cursor-theme
    - font-clear-sans-ttf
    - arc-gtk-theme
    - faba-icon-theme-mono
    - arc-icon-theme
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-impatience
    - gnome-shell-extension-topicons-plus
    - gnome-shell-extensions
    - gnome-shell
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
