name       : gnome-desktop-branding
version    : 1
release    : 1
source     :
    - https://github.com/solus-project/gnome-desktop-branding/releases/download/v1/gnome-desktop-branding-1.tar.xz : 0ce603c10e91edd8e12be49df2bbffcca03c3f4dad19c3107bc42cffc8a53643
license    : GPL-2.0
component  : desktop.gnome
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
rundeps    :
    - solus-artwork
    - breeze-cursor-theme
    - font-clear-sans-ttf
    - arc-gtk-theme
    - faba-icon-theme-mono
    - arc-icon-theme
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-dynamic-panel-transparency
    - gnome-shell-extension-impatience
    - gnome-shell-extension-topicons-plus
    - gnome-shell-extensions
    - gnome-shell
summary    : Defaults for the GNOME Desktop
description: |
     GNOME Desktop Experience Configuration
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
