name       : gnome-desktop-branding
version    : '3'
release    : 4
source     :
    - https://github.com/solus-project/gnome-desktop-branding/releases/download/v3/gnome-desktop-branding-3.tar.xz : 00b48c9dcd5ebb8fe1a68a805b8405e63404e4149280db714ad3f3912d3d15f7
license    : GPL-2.0
component  : desktop.gnome
summary    : Defaults for the GNOME Desktop
description: |
    GNOME Desktop Experience Configuration
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - gnome-shell
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-impatience
    - gnome-shell-extensions
    - gnome-shell-extension-topicons-plus
    - solus-artwork
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
