name       : gnome-desktop-branding
version    : '4'
release    : 5
source     :
    - https://github.com/solus-project/gnome-desktop-branding/releases/download/v4/gnome-desktop-branding-4.tar.xz : 599d88bca0f743494e693168f978469196a8ca9f13c835390f4ae3b3e022ee78
license    : GPL-2.0
component  : desktop.gnome
summary    : Defaults for the GNOME Desktop
description: |
    GNOME Desktop Experience Configuration
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - gnome-shell
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-impatience
    - gnome-shell-extensions
    - gnome-shell-extension-topicons-plus
    - solus-artwork
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
