name       : gnome-desktop-branding
version    : '17'
release    : 40
source     :
    - https://github.com/getsolus/gnome-desktop-branding/archive/refs/tags/v17.tar.gz : 5b7162ce2f33e649224fae5cf7a74d790a01a4d2c658d6904939e667f9ae91a7
license    : GPL-2.0-only
component  :
    - desktop.gnome
    - livecd : desktop.gnome
summary    :
    - Defaults for the GNOME Desktop
    - livecd : Solus 4.0 GNOME LiveCD configuration
description:
    - Defaults for the GNOME Desktop
    - livecd : Solus 4.0 LiveCD configuration.
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
replaces   :
    - gnome-desktop-branding-fortitude
    - gnome-desktop-branding-legacy
    - gnome-desktop-branding-material
    - gnome-desktop-branding-shared
rundeps    :
    - breeze-cursor-theme
    - font-clear-sans-ttf
    - font-hack-ttf
    - gnome-shell
    - gnome-shell-extension-impatience
    - gnome-shell-extensions
    - gnome-shell-extension-topicons-plus
    - papirus-icon-theme
    - qtstyleplugins
    - solus-artwork
    - livecd :
        - gnome-desktop-branding
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
