name       : gnome-desktop-branding
version    : 16.0
release    : 38
source     :
    - git|https://github.com/getsolus/gnome-desktop-branding.git : c21e979707f2f849d5589338df663d53ae8e43ee
license    : GPL-2.0-only
component  :
    - desktop.gnome
    - livecd : desktop.gnome
summary    :
    - Defaults for the GNOME Desktop
    - livecd : Solus 4.0 GNOME LiveCD configuration
description:
    - Defaults for the GNOME Desktop
    - livecd : Solus 4.0 LiveCD configuration.
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
replaces   :
    - gnome-desktop-branding-fortitude
    - gnome-desktop-branding-legacy
    - gnome-desktop-branding-material
    - gnome-desktop-branding-shared
rundeps    :
    - breeze-cursor-theme
    - font-clear-sans-ttf
    - font-hack-ttf
    - gnome-shell
    - gnome-shell-extension-impatience
    - gnome-shell-extensions
    - gnome-shell-extension-topicons-plus
    - papirus-icon-theme
    - qtstyleplugins
    - solus-artwork
    - livecd :
        - gnome-desktop-branding
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
