name       : gnome-desktop-branding
version    : '5'
release    : 7
source     :
    - https://github.com/solus-project/gnome-desktop-branding/releases/download/v5/gnome-desktop-branding-5.tar.xz : 738ea176636f3d848ef1a4df0f9d11a1f31002dc092eca3caf4887598905691a
license    : GPL-2.0
component  : desktop.gnome
summary    : Defaults for the GNOME Desktop
description: |
    GNOME Desktop Experience Configuration
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - gnome-shell
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-impatience
    - gnome-shell-extensions
    - gnome-shell-extension-topicons-plus
    - solus-artwork
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
